apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: pod-nginx
  namespace: kub30min
spec:
  containers:
  - name: pod-nginx        
    image: nginxdemos/hello
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
  