apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  namespace: kub30min
spec:
  selector:
    app: pod-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
  type: NodePort