apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: kub30min
spec:
  selector:
    matchLabels:
      app: deploy-nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: deploy-nginx
    spec:
      containers:
      - name: container-nginx
        image: nginxdemos/hello
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: kub30min
spec:
  ports:
  - port: 81
    targetPort: 80
  type: LoadBalancer
  selector:
    app: deploy-nginx
---
  