apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /storage/data/postgres/db