apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-identity
  namespace: gag-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi